# Generated by Django 3.1.2 on 2021-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnailUrl',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(null=True, upload_to='images/review'),
        ),
    ]
