# Generated by Django 3.1.2 on 2021-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0003_auto_20210803_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetme',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meetme.Participants'),
        ),
    ]
