# Generated by Django 3.1.2 on 2021-08-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0005_auto_20210803_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='name',
            field=models.CharField(default='Debebe', max_length=50),
            preserve_default=False,
        ),
    ]
